# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20170814_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
