# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_auto_20170814_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(related_name='liked_by', to='book_authors.User'),
        ),
    ]
